name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]

# Grant the workflow the permissions required to publish
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # allow the action to use the repository token for pushing
          persist-credentials: true
          # fetch full history so git operations succeed when pushing
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # prefer the built-in token; falls back to PAT if you set GH_PAT
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
